---

- name: Wait for ssh as Azure takes time
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'


- name: Install NTP for time sync
  package:
      state: present
      name: ntp
      use: auto
