---

- name: Wait for ssh as Azure takes time
  wait_for:
    port: 22
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'

- name: Source Variables from base role path 
  include_vars:
   file: common_vars.yml


- name: Install Common Packages
  package:
      state: present
      name: "{{ item }}"
      use: auto
  with_items:
   - "{{ web_packages }}"
  notify: restart services

- name: Generate private key
  openssl_privatekey:
   path: "{{ item.pem }}"
  with_items:
   - "{{ cert_details }}"

- name: genertate csr
  openssl_csr:
   path: "{{ item.csr }}"
   privatekey_path: "{{ item.pem }}"
   common_name: "{{inventory_hostname}}"
  with_items:
   - "{{ cert_details }}"

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
   path: "{{ item.cert }}"
   privatekey_path: "{{ item.pem }}"
   csr_path: "{{ item.csr }}"
   provider: selfsigned
   subject:
    CN: "CompanyNews.com"
  with_items:
    - "{{ cert_details }}"


- name: Copy Config templates
  template:
      dest: "{{ item.dest }}" 
      src: "{{ item.src }}"
  with_items:
  -  { src : "default.j2" , dest: "/etc/nginx/sites-enabled/default" }
  notify: restart services

- name: Copy static files/folders
  unarchive:
      src: static.zip
      dest: /var/www/html/
      group: www-data
      mode: 0755